version: "2"

services:

  node:
    build: ./app/
    volumes:
      - ./app:/nodeapp
    ports:
      - "3000:3000"

  nginx:
    build: ./nginx/
    ports:
      - 80:80
    links:
      - php
    volumes_from:
      - api

  php:
    build: ./php/
    expose:
      - 9000
    links:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: secret
    volumes_from:
      - api

  api:
    image: php:7.3-fpm
    volumes:
      - ./api:/var/www/html
    command: "true"

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes_from:
      - data
    environment:
      MYSQL_ROOT_PASSWORD: secret

  data:
    image: mysql:latest
    volumes:
      - /var/lib/mysql
    command: "true"

  phpadmin:
    image: phpmyadmin/phpmyadmin:4.8
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
     